[package]
name = "quickswitch"
version = "0.1.2"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features = ["crossterm"] }
crossterm = "0.29.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
